### ISSUE TITLE
Star `*` in Resource List

### ISSUE THREAD

**Issue by bbernays** [cloudquery/terraform-aws-cloudquery#3]
Rather than hardcoding all resources, use the `*` to ensure all resources are handled

**Comment by jasonscalia** [comment]
This looks to be in place in the latest version of:

https://github.com/cloudquery/terraform-aws-cloudquery/blob/main/tasks/config.hcl#L37

Should this be closed?

Thanks.

**Comment by bbernays** [comment]
Fixed in #10
